### ISSUE TITLE
Vulnerability in url-parse dependency

### ISSUE THREAD

**Issue by matt-cooper** [nativescript-community/universal-links#2]
GitHub reports a vulnerability in the url-parse dependency of this project:
https://github.com/advisories/GHSA-9m6j-fcg5-2442

Currently 1.4.7 is being used and apparently 1.5.0 fixes this issue.

**Comment by lrilling** [comment]
Problem still exists, Version 1.5.3. of url-parse resolves it. Updating to 1.5.3 does not seem to lead to any problems, which is why I'll create a PR for this.

**Comment by keerl** [comment]
Merged in and should be published in v2.0.4
